### ISSUE TITLE
ref.refresh cause 'A TextEditingController was used after being disposed'

### ISSUE THREAD

**Issue by nailgilaziev** [rrousselGit/river_pod#1017]
A common scenario (editing list item data and refreshing list) results in an error. 

StateProvider value is used for building Navigator pages.
After editing data and sending to the server, we need to pop current editing page and refresh data in list page.
So we need to call one after another
```dart
ref.read(editModeProvider.state).state = false; // this will cause navigator pop
ref.refresh(listFutureProvider);  // this should refresh list content
```

<details>

<summary>Simplified code sample</summary>

```dart

import 'package:flutter/material.dart';
import 'package:flutter_hooks/flutter_hooks.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';
import 'package:collection/collection.dart';

void main() {
  runApp(ProviderScope(
    child: MaterialApp(home: MyHome(), debugShowCheckedModeBanner: false),
  ));
}

// used for navigator pages
final editModeProvider = StateProvider((ref) => false);

class MyHome extends ConsumerWidget {
  const MyHome({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final editMode = ref.watch(editModeProvider);
    return Navigator(
      onPopPage: (route, dynamic result) {
        ref.read(editModeProvider.state).state = false;
        return _onPopPage(route, result);
      },
      pages: [
        ListWid(),
        if (editMode) ItemWid(),
      ].map((e) => MaterialPage<void>(child: e)).toList(),
    );
  }

  bool _onPopPage(Route<dynamic> route, dynamic result) {
    return route.didPop(result);
  }
}

final listFutureProvider = FutureProvider((ref) async {
  print('* listFutureProvider called');
  await Future<void>.delayed(Duration(seconds: 1));
  print('* listFutureProvider data ready return');
  return ['1', '2', '3', '4'];
});

final itemFutureProvider =
FutureProvider.autoDispose.family<String?, int>((ref, id) async {
  print('* itemFutureProvider($id) called');
  final list = await ref.watch(listFutureProvider.future);
  print('* itemFutureProvider($id) list watched');
  var firstOrNull = list.firstWhereOrNull((e) => e == id.toString());
  print('* itemFutureProvider($id) first null? ${firstOrNull == null}');
  return firstOrNull;
});

class ListWid extends HookConsumerWidget {
  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final listAV = ref.watch(listFutureProvider);
    print('.build ListWid listAV ${listAV}');
    final m = listAV.map(
      loading: (al) => Text('loading ${al.value}'),
      error: (_) => Text('error'),
      data: (data) => ListView(
          children: data.value
              .map(
                (e) => ListTile(
                  title: Text('v$e'),
                  onTap: () {
                    ref.read(editModeProvider.state).state = true;
                  },
                ),
              )
              .toList()),
    );
    return Scaffold(
      appBar: AppBar(),
      body: m,
    );
  }
}

class ItemWid extends HookConsumerWidget {
  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final itemAV = ref.watch(itemFutureProvider(2));
    print('.build ItemWid item av ${itemAV}');
    final m = itemAV.map(
      loading: (al) => Text('loading ${al.value}'),
      error: (_) => Text('error'),
      data: (data) {
        final controller = useTextEditingController(text: 'val');
        return Padding(
          padding: const EdgeInsets.all(8.0),
          child: TextFormField(
            controller: controller,
            decoration: InputDecoration(
                border: const OutlineInputBorder(), labelText: 'header'),
          ),
        );
      },
    );
    return Scaffold(
      appBar: AppBar(
        actions: [
          IconButton(
            onPressed: () async {
              // simulate uploading data to server
              await sendChangesToServer();
              // edit completed - return to the list page / pop current
              ref.read(editModeProvider.state).state = false;
              // re fetch modified data from server for the listview
              ref.refresh(listFutureProvider);
            },
            icon: Icon(Icons.done),
          )
        ],
      ),
      body: m,
    );
  }

  Future<void> sendChangesToServer() async {
    return Future<void>.delayed(Duration(milliseconds: 200));
  }
}
```
</details>

**Expected behavior**
No errors should fire. Right? There is no clear understanding why this error happen.

**Error**
A TextEditingController was used after being disposed.

<details>

<summary>logs</summary>
Debug service listening on ws://127.0.0.1:61507/nZXv2zWKoqE=/ws
Syncing files to device macOS...
flutter: * listFutureProvider called
flutter: .build ListWid listAV AsyncLoading<List<String>>()
flutter: * listFutureProvider data ready return
flutter: .build ListWid listAV AsyncData<List<String>>(value: [1, 2, 3, 4])
flutter: * itemFutureProvider(2) called
flutter: .build ItemWid item av AsyncLoading<String?>()
flutter: .build ListWid listAV AsyncData<List<String>>(value: [1, 2, 3, 4])
flutter: * itemFutureProvider(2) list watched
flutter: * itemFutureProvider(2) first null? false
flutter: .build ItemWid item av AsyncData<String?>(value: 2)
flutter: * listFutureProvider called
flutter: * itemFutureProvider(2) called
flutter: .build ListWid listAV AsyncLoading<List<String>>()
flutter: .build ItemWid item av AsyncLoading<String?>()

======== Exception caught by widgets library =======================================================
The following assertion was thrown while finalizing the widget tree:
A TextEditingController was used after being disposed.

Once you have called dispose() on a TextEditingController, it can no longer be used.
When the exception was thrown, this was the stack: 
#0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:114:9)
#1      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:120:6)
#2      ChangeNotifier.removeListener (package:flutter/src/foundation/change_notifier.dart:233:12)
#3      EditableTextState.dispose (package:flutter/src/widgets/editable_text.dart:1781:23)
#4      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:4818:11)
#5      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1883:13)
#6      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#7      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
#8      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#9      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#10     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6110:14)
#11     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#12     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#13     Iterable.forEach (dart:core/iterable.dart:279:35)
#14     _DecorationElement.visitChildren (package:flutter/src/material/input_decorator.dart:1601:24)
#15     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#16     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#17     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
#18     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#19     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#20     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
#21     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#22     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#23     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6110:14)
#24     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#25     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#26     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
#27     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#28     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#29     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
#30     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#31     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#32     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6110:14)
#33     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#34     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#35     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
#36     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#37     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#38     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6110:14)
#39     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#40     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#41     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6110:14)
#42     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#43     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#44     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
#45     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#46     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#47     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6110:14)
#48     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#49     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#50     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
#51     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#52     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#53     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
#54     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#55     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#56     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
#57     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#58     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#59     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6110:14)
#60     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#61     ListIterable.forEach (dart:_internal/iterable.dart:39:13)
#62     _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:1892:25)
#63     BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:2837:27)
#64     BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2468:15)
#65     BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:2836:7)
#66     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:884:19)
#67     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#68     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145:15)
#69     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#70     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
#74     _invoke (dart:ui/hooks.dart:150:10)
#75     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
#76     _drawFrame (dart:ui/hooks.dart:114:31)
(elided 3 frames from dart:async)
====================================================================================================
flutter: * listFutureProvider data ready return
flutter: * itemFutureProvider(2) list watched
flutter: * itemFutureProvider(2) first null? false
flutter: .build ListWid listAV AsyncData<List<String>>(value: [1, 2, 3, 4])
</details>

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.0.1 21A559 darwin-x64, locale en-RU)
    • Flutter version 2.8.1 at /Users/ng/Tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (5 days ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

```
```
flutter_hooks: ^0.18.1
hooks_riverpod: ^1.0.1
```

https://user-images.githubusercontent.com/2749021/146987275-9c43b9eb-8a0e-4057-b950-f9f622c95786.mov

**Comment by nailgilaziev** [comment]
I understood what the problem is. 
here I use hooks via condition. This is violation
```dart
final m = listAV.map(
      loading: (al) => Text('loading ${al.value}'),
      error: (_) => Text('error'),
      data: (data) => ListView(
          children: data.value
              .map(
                (e) => ListTile(
                  title: Text('v$e'),
                  onTap: () {
                    ref.read(editModeProvider.state).state = true;
                  },
                ),
              )
              .toList()),
    );
```
