### ISSUE TITLE
`overrideWithProvider` allows subtype at compile time, but fails at runtime

### ISSUE THREAD

**Issue by ElteHupkes** [rrousselGit/river_pod#1100]
**Describe the bug**
Overriding a provider with `provider.overrideWithProvider(otherProvider);` compiles if `provider is Provider<Foo>` and `otherProvider` is `Provider<Bar extends Foo>`. At runtime, this override throws an exception when used. I'm currently using the latest version of `hooks_riverpod` (v1.0.3).

**To Reproduce**
This compiles:
```dart
import 'package:flutter/material.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';

void main() {
  runApp(const ProviderScope(child: MyApp()));
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: ProviderScope(
          overrides: [fooProvider.overrideWithProvider(barProvider)],
          child: Consumer(
            builder: (context, ref, _) {
              final test = ref.watch(fooProvider);
              return const Center(
                child: Text('Runtime error.'),
              );
            },
          ),
        ),
      ),
    );
  }
}

class Foo {}

class Bar extends Foo {}

final fooProvider = Provider<Foo>((ref) => Foo());
final barProvider = Provider<Bar>((ref) => Bar());
```

but throws:

```
======== Exception caught by widgets library =======================================================
The following _TypeError was thrown building Consumer(dirty, dependencies: [UncontrolledProviderScope], state: _ConsumerState#9dbf0):
type 'Provider<Foo>' is not a subtype of type 'ProviderBase<Bar>' of 'value'

The relevant error-causing widget was: 
  Consumer Consumer:file:///Users/elte/StudioProjects/sandbox/lib/main.dart:17:18
When the exception was thrown, this was the stack: 
#0      ProviderElementBase._origin= (package:riverpod/src/framework/provider_base.dart)
#1      _StateReader._create (package:riverpod/src/framework/container.dart:102:11)
#2      _StateReader.getElement (package:riverpod/src/framework/container.dart:92:52)
#3      ProviderContainer.readProviderElement.<anonymous closure> (package:riverpod/src/framework/container.dart:471:38)
#4      ProviderContainer.readProviderElement (package:riverpod/src/framework/container.dart:504:6)
#5      ProviderContainer.listen (package:riverpod/src/framework/container.dart:327:21)
#6      ConsumerStatefulElement.watch.<anonymous closure> (package:flutter_riverpod/src/consumer.dart:449:25)
#7      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:453:23)
#8      ConsumerStatefulElement.watch (package:flutter_riverpod/src/consumer.dart:442:26)
#9      MyApp.build.<anonymous closure> (package:sandbox/main.dart:19:32)
#10     Consumer.build (package:flutter_riverpod/src/consumer.dart:269:20)
#11     _ConsumerState.build (package:flutter_riverpod/src/consumer.dart:371:19)
#12     StatefulElement.build (package:flutter/src/widgets/framework.dart:4705:27)
#13     ConsumerStatefulElement.build (package:flutter_riverpod/src/consumer.dart:431:20)
#14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4588:15)
#15     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
#16     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#17     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4566:5)
#18     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4754:11)
#19     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4561:5)
...     Normal element mounting (7 frames)
#26     _UncontrolledProviderScopeElement.mount (package:flutter_riverpod/src/framework.dart:250:11)
...     Normal element mounting (27 frames)
#53     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3631:14)
#54     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6261:36)
#55     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6272:32)
...     Normal element mounting (108 frames)
#163    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3631:14)
#164    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6261:36)
#165    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6272:32)
...     Normal element mounting (173 frames)
#338    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3631:14)
#339    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6261:36)
#340    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6272:32)
...     Normal element mounting (397 frames)
#737    _UncontrolledProviderScopeElement.mount (package:flutter_riverpod/src/framework.dart:250:11)
...     Normal element mounting (9 frames)
#746    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3631:14)
#747    Element.updateChild (package:flutter/src/widgets/framework.dart:3383:18)
#748    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1198:16)
#749    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1167:5)
#750    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1112:18)
#751    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2531:19)
#752    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1111:13)
#753    WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:944:7)
#754    WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:924:7)
(elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
====================================================================================================
```

I run into this issue on occasion when I override a provider with another provider that returns a mock extending the original type, but don't explicitly specify the type argument. For instance, I override `Provider((ref) => Foo())` with `Provider((ref) => MockFoo())` where `MockFoo extends Foo` (but obviously something more complicated than that to warrant `overrideWithProvider` to begin with). Changing to `Provider<Foo>((ref) => MockFoo())` gets rid of the runtime error.

**Expected behavior**
Either this should fail at compile time, if the provider type needs to match exactly, or this should not fail at runtime. I can't estimate the consequences of either, but both behaviors would seem perfectly fine to me.

**Comment by rrousselGit** [comment]
That definitely shouldn't happen. I'll see what I can do

**Comment by ElteHupkes** [comment]
Thanks Remi! All your contributions are much appreciated.
