### ISSUE TITLE
riverpod migrate: FileSystemException: Failed to decode data using encoding 'utf-8' because of goldens

### ISSUE THREAD

**Issue by GP4cK** [rrousselGit/river_pod#1114]
**Describe the bug**
I'm trying to migrate a project to riverpod v1 using the migration tool.
Unfortunately, when I run `riverpod migrate`, the program crashes with the FileSystemException because of the golden images in our tests.

<details>
<summary>Error log</summary>

```sh
[INFO] Setting up analysis contexts...
[INFO] done
searching...
Unhandled exception:
FileSystemException: Failed to decode data using encoding 'utf-8', path = '/Users/toto/github/flutter/my_project/test/lib/web/widgets/photo.dart/photo_with_preview_square.png'
#0      _File._tryDecode (dart:io/file_impl.dart:564:7)
#1      _File.readAsStringSync (dart:io/file_impl.dart:584:7)
#2      FileContext.sourceText (package:codemod/src/file_context.dart:42:45)
#3      FileContext.sourceText (package:codemod/src/file_context.dart)
#4      FileContext.sourceFile (package:codemod/src/file_context.dart:39:29)
#5      FileContext.sourceFile (package:codemod/src/file_context.dart)
#6      _runInteractiveCodemod (package:codemod/src/run_interactive_codemod.dart:317:37)
<asynchronous suspension>
#7      MigrateCommand.run (package:riverpod_cli/src/migrate.dart:80:5)
<asynchronous suspension>
#8      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
```

</details>

**To Reproduce**
Create a project, create a test with a golden and use the migration tool.

**Expected behavior**
The tool should ignore .png file (or only parse .dart files?)

**Comment by GP4cK** [comment]
Sorry sorry it's because one of the folder had `.dart` in it. I renamed it and was able to run the tool.
