### ISSUE TITLE
Streambuilder shows a red error screen for less than a second when it should not

### ISSUE THREAD

**Issue by muezz** [rrousselGit/river_pod#1297]
**Bug Description**
I am using StateNotifier in Riverpod to create a ViewModel class which basically has just one method to fetch a stream of data from Firestore. For some reason, when I click on the desired screen, I see a red screen for a second and then the data shows up from firestore the way it is supposed to.

**To Reproduce**
This is the file with all of my riverpods:
```dart
final authServiceRiverpod = Provider<AuthService>(
  (ref) => AuthService(),
);
final firestoreServiceRiverpod = Provider<FirestoreService>(
  (ref) => FirestoreService(),
);
final transactionsViewModelRiverpod =
    StateNotifierProvider<TransactionsViewModel, TransactionsState>(
  ((ref) {
    var _firestoreService = ref.watch(firestoreServiceRiverpod);
    return TransactionsViewModel(_firestoreService);
  }),
);
```

These are the ViewModel and State Classes:
```dart
class TransactionsState {
  const TransactionsState();
}

class TransactionsInitialState extends TransactionsState {
  const TransactionsInitialState();
}

class TransactionsLoadingState extends TransactionsState {
  const TransactionsLoadingState();
}

class TransactionsLoadedState extends TransactionsState {
  final Stream<List<TransactionModel>> streamOfLoadedTransactions;
  const TransactionsLoadedState(
    this.streamOfLoadedTransactions,
  );

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;

    return other is TransactionsLoadedState &&
        other.streamOfLoadedTransactions == streamOfLoadedTransactions;
  }

  @override
  int get hashCode => streamOfLoadedTransactions.hashCode;
}

class TransactionsErrorState extends TransactionsState {
  final String errorMessage;
  const TransactionsErrorState(
    this.errorMessage,
  );

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;

    return other is TransactionsErrorState &&
        other.errorMessage == errorMessage;
  }

  @override
  int get hashCode => errorMessage.hashCode;
}

class TransactionsViewModel extends StateNotifier<TransactionsState> {
  final FirestoreService _firestoreService;

  TransactionsViewModel(this._firestoreService)
      : super(const TransactionsInitialState()) {
    queryTransactions();
  }

  Future queryTransactions() async {
    try {
      state = const TransactionsLoadingState();

      debugPrint('queryTransactions was called!');
      Future.delayed(const Duration(seconds: 10));
      final Stream<List<TransactionModel>> transactionsQueryResponse =
          _firestoreService.transactions;

      state = TransactionsLoadedState(transactionsQueryResponse);
    } on FirebaseException catch (e) {
      state = TransactionsErrorState(
        e.message.toString(),
      );
    }
  }
}
```
This is where this stream is used:
```dart
class TransactionsPage extends StatelessWidget {
  const TransactionsPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: buildAppBar(title: 'Transactions'),
      bottomNavigationBar: buildBottomNavBar(context: context),
      floatingActionButton: buildFloatingActionButton(context: context),
      floatingActionButtonLocation: FloatingActionButtonLocation.centerDocked,
      body: SafeArea(
        child: Consumer(
          builder: (context, ref, child) {
            final state = ref.watch(transactionsViewModelRiverpod);

            if (state is TransactionsInitialState) {
              debugPrint('Initial Transactions State');
              return buildLoadingWidget();
            } else if (state is TransactionsLoadingState) {
              debugPrint('Transactions are Loading');
              return buildLoadingWidget();
            } else if (state is TransactionsLoadedState) {
              debugPrint('Transactions are Loaded');
              return StreamBuilder<List<TransactionModel>>(
                  stream: state.streamOfLoadedTransactions,
                  builder: (context, snapshot) {
                    return ListView.builder(
                      itemCount: snapshot.data!.length,
                      itemBuilder: (context, index) =>
                          buildTransactionDetailsButton(
                        context: context,
                        title: categoryNames[snapshot.data![index].category]!,
                        debitAcc: allVariables
                            .firstWhere(
                              (element) =>
                                  element.variableName ==
                                  snapshot.data![index].debitAccount,
                            )
                            .actualName,
                        creditAcc: allVariables
                            .firstWhere(
                              (element) =>
                                  element.variableName ==
                                  snapshot.data![index].creditAccount,
                            )
                            .actualName,
                        amount: snapshot.data![index].amount.toString(),
                      ),
                    );
                  });
            } else {
              // (state is TransactionsError)
              debugPrint('There was an error');
              return buildErrorWidget();
            }
          },
        ),
      ),
    );
  }
}

```
**Expected behavior**
This is the Output from the debug Console:
```
Launching lib/main.dart on AOSP on IA Emulator in debug mode...
lib/main.dart:1
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:44793/XlDsJ16mGUU=/ws
I/FirebaseApp( 6038): Device unlocked: initializing all Firebase APIs for app [DEFAULT]
I/FirebaseAuth( 6038): [FirebaseAuth:] Preparing to create service connection to fallback implementation
I/flutter ( 6038): []
D/eglCodecCommon( 6038): setVertexArrayObject: set vao to 0 (0) 0 0
D/EGL_emulation( 6038): eglMakeCurrent: 0xde385ba0: ver 3 0 (tinfo 0xde3ff5a0)
D/eglCodecCommon( 6038): setVertexArrayObject: set vao to 0 (0) 1 2
I/flutter ( 6038): [BeamPage("null", [</dashboard>], null)]
I/flutter ( 6038): queryTransactions was called!
I/flutter ( 6038): transactions getter was called!
I/flutter ( 6038): Transactions are Loaded

════════ Exception caught by widgets library ═══════════════════════════════════
The following _CastError was thrown building StreamBuilder<List<TransactionModel>>(dirty, state: _StreamBuilderBaseState<List<TransactionModel>, AsyncSnapshot<List<TransactionModel>>>#b1081):
Null check operator used on a null value

The relevant error-causing widget was
StreamBuilder<List<TransactionModel>>
package:franchise_manager/…/pages/page_transactions.dart:38
When the exception was thrown, this was the stack
#0      TransactionsPage.build.<anonymous closure>.<anonymous closure>
package:franchise_manager/…/pages/page_transactions.dart:42
#1      StreamBuilder.build
package:flutter/…/widgets/async.dart:442
#2      _StreamBuilderBaseState.build
package:flutter/…/widgets/async.dart:124
#3      StatefulElement.build
package:flutter/…/widgets/framework.dart:4870
#4      ComponentElement.performRebuild
package:flutter/…/widgets/framework.dart:4754
#5      StatefulElement.performRebuild
package:flutter/…/widgets/framework.dart:4928
#6      Element.rebuild
package:flutter/…/widgets/framework.dart:4477
#7      ComponentElement._firstBuild
package:flutter/…/widgets/framework.dart:4735
#8      StatefulElement._firstBuild
package:flutter/…/widgets/framework.dart:4919
#9      ComponentElement.mount
package:flutter/…/widgets/framework.dart:4729
...     Normal element mounting (42 frames)
#51     Element.inflateWidget
package:flutter/…/widgets/framework.dart:3790
#52     MultiChildRenderObjectElement.inflateWidget
package:flutter/…/widgets/framework.dart:6422
#53     MultiChildRenderObjectElement.mount
package:flutter/…/widgets/framework.dart:6433
...     Normal element mounting (261 frames)
#314    Element.inflateWidget
package:flutter/…/widgets/framework.dart:3790
#315    MultiChildRenderObjectElement.inflateWidget
package:flutter/…/widgets/framework.dart:6422
#316    Element.updateChild
package:flutter/…/widgets/framework.dart:3540
#317    RenderObjectElement.updateChildren
package:flutter/…/widgets/framework.dart:5845
#318    MultiChildRenderObjectElement.update
package:flutter/…/widgets/framework.dart:6445
#319    Element.updateChild
package:flutter/…/widgets/framework.dart:3501
#320    ComponentElement.performRebuild
package:flutter/…/widgets/framework.dart:4780
#321    StatefulElement.performRebuild
package:flutter/…/widgets/framework.dart:4928
#322    Element.rebuild
package:flutter/…/widgets/framework.dart:4477
#323    StatefulElement.update
package:flutter/…/widgets/framework.dart:4960
#324    Element.updateChild
package:flutter/…/widgets/framework.dart:3501
#325    ComponentElement.performRebuild
package:flutter/…/widgets/framework.dart:4780
#326    Element.rebuild
package:flutter/…/widgets/framework.dart:4477
#327    ProxyElement.update
package:flutter/…/widgets/framework.dart:5108
#328    Element.updateChild
package:flutter/…/widgets/framework.dart:3501
#329    ComponentElement.performRebuild
package:flutter/…/widgets/framework.dart:4780
#330    Element.rebuild
package:flutter/…/widgets/framework.dart:4477
#331    ProxyElement.update
package:flutter/…/widgets/framework.dart:5108
#332    _InheritedNotifierElement.update
package:flutter/…/widgets/inherited_notifier.dart:111
#333    Element.updateChild
package:flutter/…/widgets/framework.dart:3501
#334    SingleChildRenderObjectElement.update
package:flutter/…/widgets/framework.dart:6291
#335    Element.updateChild
package:flutter/…/widgets/framework.dart:3501
#336    ComponentElement.performRebuild
package:flutter/…/widgets/framework.dart:4780
#337    StatefulElement.performRebuild
package:flutter/…/widgets/framework.dart:4928
#338    Element.rebuild
package:flutter/…/widgets/framework.dart:4477
#339    StatefulElement.update
package:flutter/…/widgets/framework.dart:4960
#340    Element.updateChild
package:flutter/…/widgets/framework.dart:3501
#341    SingleChildRenderObjectElement.update
package:flutter/…/widgets/framework.dart:6291
#342    Element.updateChild
package:flutter/…/widgets/framework.dart:3501
#343    SingleChildRenderObjectElement.update
package:flutter/…/widgets/framework.dart:6291
#344    Element.updateChild
package:flutter/…/widgets/framework.dart:3501
#345    ComponentElement.performRebuild
package:flutter/…/widgets/framework.dart:4780
#346    Element.rebuild
package:flutter/…/widgets/framework.dart:4477
#347    ProxyElement.update
package:flutter/…/widgets/framework.dart:5108
#348    Element.updateChild
package:flutter/…/widgets/framework.dart:3501
#349    ComponentElement.performRebuild
package:flutter/…/widgets/framework.dart:4780
#350    StatefulElement.performRebuild
package:flutter/…/widgets/framework.dart:4928
#351    Element.rebuild
package:flutter/…/widgets/framework.dart:4477
#352    StatefulElement.update
package:flutter/…/widgets/framework.dart:4960
#353    Element.updateChild
package:flutter/…/widgets/framework.dart:3501
#354    ComponentElement.performRebuild
package:flutter/…/widgets/framework.dart:4780
#355    Element.rebuild
package:flutter/…/widgets/framework.dart:4477
#356    StatelessElement.update
package:flutter/…/widgets/framework.dart:4834
#357    Element.updateChild
package:flutter/…/widgets/framework.dart:3501
#358    ComponentElement.performRebuild
package:flutter/…/widgets/framework.dart:4780
#359    Element.rebuild
package:flutter/…/widgets/framework.dart:4477
#360    StatelessElement.update
package:flutter/…/widgets/framework.dart:4834
#361    Element.updateChild
package:flutter/…/widgets/framework.dart:3501
#362    ComponentElement.performRebuild
package:flutter/…/widgets/framework.dart:4780
#363    Element.rebuild
package:flutter/…/widgets/framework.dart:4477
#364    ProxyElement.update
package:flutter/…/widgets/framework.dart:5108
#365    Element.updateChild
package:flutter/…/widgets/framework.dart:3501
#366    ComponentElement.performRebuild
package:flutter/…/widgets/framework.dart:4780
#367    Element.rebuild
package:flutter/…/widgets/framework.dart:4477
#368    ProxyElement.update
package:flutter/…/widgets/framework.dart:5108
#369    Element.updateChild
package:flutter/…/widgets/framework.dart:3501
#370    ComponentElement.performRebuild
package:flutter/…/widgets/framework.dart:4780
#371    StatefulElement.performRebuild
package:flutter/…/widgets/framework.dart:4928
#372    Element.rebuild
package:flutter/…/widgets/framework.dart:4477
#373    BuildOwner.buildScope
package:flutter/…/widgets/framework.dart:2659
#374    WidgetsBinding.drawFrame
package:flutter/…/widgets/binding.dart:882
#375    RendererBinding._handlePersistentFrameCallback
package:flutter/…/rendering/binding.dart:363
#376    SchedulerBinding._invokeFrameCallback
package:flutter/…/scheduler/binding.dart:1144
#377    SchedulerBinding.handleDrawFrame
package:flutter/…/scheduler/binding.dart:1081
#378    SchedulerBinding._handleDrawFrame
package:flutter/…/scheduler/binding.dart:995
#382    _invoke (dart:ui/hooks.dart:151:10)
#383    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#384    _drawFrame (dart:ui/hooks.dart:115:31)
(elided 3 frames from dart:async)
════════════════════════════════════════════════════════════════════════════════
W/DynamiteModule( 6038): Local module descriptor class for providerinstaller not found.
I/DynamiteModule( 6038): Considering local module providerinstaller:0 and remote module providerinstaller:0
W/ProviderInstaller( 6038): Failed to load providerinstaller module: No acceptable module found. Local version is 0 and remote version is 0.
W/anchise_manage( 6038): Unknown chunk type '200'.
W/anchise_manage( 6038): Accessing hidden field Ljava/nio/Buffer;->address:J (light greylist, reflection)
I/anchise_manage( 6038): The ClassLoaderContext is a special shared library.
I/chatty  ( 6038): uid=10086(com.abdulmuezz.franchise_manager) AsyncTask #2 identical 1 line
I/anchise_manage( 6038): The ClassLoaderContext is a special shared library.
V/NativeCrypto( 6038): Registering com/google/android/gms/org/conscrypt/NativeCrypto's 294 native methods...
W/anchise_manage( 6038): Accessing hidden method Ljava/security/spec/ECParameterSpec;->getCurveName()Ljava/lang/String; (light greylist, reflection)
D/NetworkSecurityConfig( 6038): No Network Security Config specified, using platform default
I/ProviderInstaller( 6038): Installed default security provider GmsCore_OpenSSL
W/anchise_manage( 6038): Accessing hidden field Ljava/net/Socket;->impl:Ljava/net/SocketImpl; (light greylist, reflection)
W/anchise_manage( 6038): Accessing hidden method Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard; (light greylist, linking)
W/anchise_manage( 6038): Accessing hidden method Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V (light greylist, linking)
W/anchise_manage( 6038): Accessing hidden method Ljava/security/spec/ECParameterSpec;->setCurveName(Ljava/lang/String;)V (light greylist, reflection)
W/anchise_manage( 6038): Accessing hidden method Ldalvik/system/BlockGuard;->getThreadPolicy()Ldalvik/system/BlockGuard$Policy; (light greylist, linking)
W/anchise_manage( 6038): Accessing hidden method Ldalvik/system/BlockGuard$Policy;->onNetwork()V (light greylist, linking)
Application finished.
Exited (sigterm)
```

I am following this tutorial from Resocoder: https://resocoder.com/2020/12/11/flutter-statenotifier-riverpod-tutorial-immutable-state-management/#t-1607603232272

He uses a Future to implement this but I want to use streams. I also understand that when using Streambuilders, the common practice is to use a condition that checks whether the snapshot has any data or not. However, I am not doing that because if the state is `TransactionLoadedState` then I know the snapshot already has data.

What am I doing wrong here?

Is there a better way to handle this issue?

**Comment by rrousselGit** [comment]
You didn't handle loading state in your StreamBuilder. Streams emit their state asynchronously, so there 's a little bit of time where `snapshot.data` is null

**Comment by muezz** [comment]
Thats what I thought too but I am confused because the streambuilder is only called when the state is `TransactionLoadedState` and that state is only there when the stream getter has been successfully called. There should be no time where the stream is null...I think.

**Comment by muezz** [comment]
I did not know that. Is there a better way to handle this situation? I feel like adding a `hasData` conditional within the stream builder makes the state management through riverpod kid of redundant. Are there any alternatives or any resources I can follow?
