### ISSUE TITLE
FutureProvider crashes on compile on web if return type is dynamic

### ISSUE THREAD

**Issue by hamishjohnson** [rrousselGit/river_pod#1339]
**Describe the bug**
There's a small bug that I found where FutureProviders crash on compiling web version when the return type is dynamic.

**To Reproduce**
```
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

void main() {
  runApp(const ProviderScope(child: MyApp()));
}

class MyApp extends ConsumerWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final value = ref.watch(stringProvider);

    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(body: Text(value.value ?? '')),
    );
  }
}

const condition = false;

final stringProvider = FutureProvider<String>((ref) {
  if (condition) return 'child'; // <==== This line is what causes the bug

  return future();
});

Future<String> future() async {
  await Future.delayed(const Duration(seconds: 1));

  return 'done';
}
```

**Expected behavior**
Run on mobile, works fine. Run on web, compile crashes.

When adding 'async' to the provided create function, it works fine.

Now, I'm not really sure what the correct solution to this is, but IMO really a FutureProvider should probably require returning a Future so that linting catches the issue. Is there some reason that it only requires FutureOr - `FutureOr<String> Function(FutureProviderRef<String>) _create`  ?

<details>
<summary>Error</summary>

```
Launching lib[/main.dart]() on Chrome in debug mode...
lib/main.dart:1
Unhandled exception:
Unsupported operation: Undetermined Nullability
#0      ProgramCompiler._emitFutureOrType (package:dev_compiler[/src/kernel/compiler.dart:3057:7]())
#1      ProgramCompiler.visitFutureOrType (package:dev_compiler[/src/kernel/compiler.dart:2948:11]())
#2      FutureOrType.accept (package:kernel[/ast.dart:11519:42]())
#3      ProgramCompiler._emitType (package:dev_compiler[/src/kernel/compiler.dart:2847:54]())
#4      ProgramCompiler.visitFunctionType (package:dev_compiler[/src/kernel/compiler.dart:3138:22]())
#5      ProgramCompiler._emitFunctionTagged (package:dev_compiler[/src/kernel/compiler.dart:2803:19]())
#6      ProgramCompiler.visitFunctionExpression (package:dev_compiler[/src/kernel/compiler.dart:6186:12]())
#7      FunctionExpression.accept (package:kernel[/ast.dart:8292:44]())
#8      ProgramCompiler._visitExpression (package:dev_compiler[/src/kernel/compiler.dart:3870:20]())
#9      ProgramCompiler._emitArgumentList (package:dev_compiler[/src/kernel/compiler.dart:5614:11]())

#10     ProgramCompiler.visitConstructorInvocation (package:dev_compiler[/src/kernel/compiler.dart:5761:9]())
#11     ConstructorInvocation.accept (package:kernel[/ast.dart:6392:44]())
#12     ProgramCompiler._visitExpression (package:dev_compiler[/src/kernel/compiler.dart:3870:20]())
#13     ProgramCompiler._visitInitializer (package:dev_compiler[/src/kernel/compiler.dart:1786:11]())
#14     ProgramCompiler._emitStaticFieldInitializer.<anonymous closure> (package:dev_compiler[/src/kernel/compiler.dart:2366:23]())
#15     ProgramCompiler._withLetScope (package:dev_compiler[/src/kernel/compiler.dart:2376:25]())
#16     ProgramCompiler._emitStaticFieldInitializer (package:dev_compiler[/src/kernel/compiler.dart:2364:40]())
#17     ProgramCompiler._emitLazyFields (package:dev_compiler[/src/kernel/compiler.dart:2339:43]())
#18     ProgramCompiler._emitTopLevelFields (package:dev_compiler[/src/kernel/compiler.dart:2323:21]())
#19     ProgramCompiler._emitLibrary (package:dev_compiler[/src/kernel/compiler.dart:573:7]())
#20     List.forEach (dart:core-patch[/growable_array.dart:433:8]())
#21     ProgramCompiler.emitModule (package:dev_compiler[/src/kernel/compiler.dart:431:15]())
#22     JavaScriptBundler.compile (package:frontend_server[/src/javascript_bundle.dart:152:33]())
<asynchronous suspension>
#23     FrontendCompiler.writeJavascriptBundle (package:frontend_server[/frontend_server.dart:665:32]())

<asynchronous suspension>
#24     FrontendCompiler.compile (package:frontend_server[/frontend_server.dart:573:9]())
<asynchronous suspension>
#25     listenAndCompile.<anonymous closure> (package:frontend_server[/frontend_server.dart:1154:11]())
<asynchronous suspension>

the Dart compiler exited unexpectedly.
Exited (sigterm)
Failed to compile application.
```

</details>

**Comment by rrousselGit** [comment]
Coul you share your error?

**Comment by hamishjohnson** [comment]
Yup added the error to the end in the toggle dropwdonw

**Comment by rrousselGit** [comment]
This looks like a bug on the Dart web compiler.
After all it's the compiler that crashes

I'd suggest raising an issue in the Dart SDK with the same code (possibly without Riverpod if you can).

**Comment by hamishjohnson** [comment]
Okidoki 👍🏼
