### ISSUE TITLE
Widget test fails with pending timers with auto-dispose provider

### ISSUE THREAD

**Issue by tomgilder** [rrousselGit/river_pod#1941]
Hi, I've come across an issue that's making it very hard to write widget tests.

Here's a full example, using 2.1.1:

```dart
final provider1 = Provider.autoDispose((ref) {
  ref.keepAlive();

  ref.watch(streamProvider);
});

final streamProvider = StreamProvider.autoDispose((ref) async* {});

void main() {
  testWidgets('Riverpod test', (tester) async {
    await tester.pumpWidget(
      ProviderScope(
        child: Consumer(
          builder: (context, ref, child) {
            ref.watch(provider1);

            return const SizedBox();
          },
        ),
      ),
    );
  });
}
```

The test fails due to a pending timer created by the scheduler, and `pumpAndSettle()` doesn't fix it.

My understanding of what's going on:

* `UncontrolledProviderScope` is unmounted, resetting the `vsyncOverride`
* `container.disposed()` is called, which then schedules a dispose for the stream controller
* Because that scheduled dispose isn't using `flutterVsync`, a timer is created which isn't cleared up

I haven't been able to find a workaround to this.

Full test output:

```
Pending timers:
Timer (duration: 0:00:00.000000, periodic: false), created:
#0      new FakeTimer._ (package:fake_async/fake_async.dart:308:62)
#1      FakeAsync._createTimer (package:fake_async/fake_async.dart:252:27)
#2      FakeAsync.run.<anonymous closure> (package:fake_async/fake_async.dart:185:19)
#7      _defaultVsync (package:riverpod/src/framework/scheduler.dart:9:3)
#8      _ProviderScheduler._scheduleTask (package:riverpod/src/framework/scheduler.dart:42:10)
#9      _ProviderScheduler.scheduleProviderDispose (package:riverpod/src/framework/scheduler.dart:73:5)
#10     AutoDisposeProviderElementMixin.mayNeedDispose (package:riverpod/src/framework/auto_dispose.dart:40:29)
#11     ProviderElementBase._onRemoveListener (package:riverpod/src/framework/element.dart:894:5)
#12     ProviderElementBase.dispose (package:riverpod/src/framework/element.dart:874:15)
#13     ProviderContainer.dispose (package:riverpod/src/framework/container.dart:656:15)
#14     ProviderScopeState.dispose (package:flutter_riverpod/src/framework.dart:258:15)
#15     StatefulElement.unmount (package:flutter/src/widgets/framework.dart:5105:11)
#16     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1917:13)
#17     ListIterable.forEach (dart:_internal/iterable.dart:39:13)
#18     _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:1926:25)
#19     BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2523:15)
#20     BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:2947:7)
#21     AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1211:19)
#22     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:378:5)
#23     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175:15)
#24     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1104:9)
#25     AutomatedTestWidgetsFlutterBinding.scheduleWarmUpFrame (package:flutter_test/src/binding.dart:1137:5)
#26     runApp (package:flutter/src/widgets/binding.dart:1038:7)
#27     TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:848:7)
<asynchronous suspension>
(elided 4 frames from dart:async)

══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown running a test:
A Timer is still pending even after the widget tree was disposed.
'package:flutter_test/src/binding.dart':
Failed assertion: line 1299 pos 12: '!timersPending'

When the exception was thrown, this was the stack:
#2      AutomatedTestWidgetsFlutterBinding._verifyInvariants (package:flutter_test/src/binding.dart:1299:12)
#3      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:857:7)
<asynchronous suspension>
(elided 2 frames from class _AssertionError)

The test description was:
  Riverpod test
════════════════════════════════════════════════════════════════════════════════════════════════════
Test failed. See exception logs above.
```

**Comment by rrousselGit** [comment]
You can add an empty `await tester.pumpWidget(Container());` at the end as workaround.

**Comment by rrousselGit** [comment]
```
  testWidgets('Riverpod test', (tester) async {
    await tester.pumpWidget(
      ProviderScope(
        child: Consumer(
          builder: (context, ref, child) {
            ref.watch(provider1);

            return const SizedBox();
          },
        ),
      ),
    );

    await tester.pumpWidget(Container());
    await tester.pumpAndSettle();
  });
```

**Comment by KoheiKanagu** [comment]
I found another solution.
`createContainer` is this https://riverpod.dev/docs/essentials/testing#unit-tests

```dart
  testWidgets('Riverpod test', (tester) async {
    final container = createContainer();

    return tester.pumpWidget(
      UncontrolledProviderScope(
        container: container,
        child: Consumer(
          builder: (context, ref, child) {
            ref.watch(provider1);

            return const SizedBox();
          },
        ),
      ),
    );
  });
```

**Comment by JoostVisser** [comment]
It seems that with version 2.4.8 I required the aforementioned workaround again (pumping an empty container) together with `tester.runAync`. Version 2.4.7 does not have this problem for me.

**Comment by rrousselGit** [comment]
@JoostVisser Please share a full sample for this. I don't have the issue

**Comment by rrousselGit** [comment]
I've found the source of the pending timer issue thanks to OP's reproducible example. A fix should land soon

**Comment by JoostVisser** [comment]
@rrousselGit Sadly, the fix in 2.4.9 did not seem to work for me. 

Here's a full example of the issue.

```dart
import 'package:fluent_ui/fluent_ui.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';

class BoolController extends AutoDisposeNotifier<bool> {
  bool build() => false;
}

final boolProvider = AutoDisposeNotifierProvider<BoolController, bool>(() {
  return BoolController();
});

void main() {
  testWidgets('Riverpod test', (tester) async {
    await tester.pumpWidget(
      ProviderScope(
        child: Consumer(
          builder: (context, ref, child) {
            ref.watch(boolProvider);

            return const SizedBox();
          },
        ),
        parent: ProviderContainer(),
      ),
    );
  });
}
```

Specifically, providing a `ProviderContainer` in the parents seems to break things. 

The error is similar to the OP's, although the stacktrace differs a bit.

```
Pending timers:
Timer (duration: 0:00:00.000000, periodic: false), created:
#0      new FakeTimer._ (package:fake_async/fake_async.dart:308:62)
#1      FakeAsync._createTimer (package:fake_async/fake_async.dart:252:27)
#2      FakeAsync.run.<anonymous closure> (package:fake_async/fake_async.dart:185:19)
#7      _defaultVsync (package:riverpod/src/framework/scheduler.dart:9:3)
#8      ProviderScheduler._scheduleTask (package:riverpod/src/framework/scheduler.dart:74:10)
#9      ProviderScheduler.scheduleProviderDispose (package:riverpod/src/framework/scheduler.dart:107:5)
#10     AutoDisposeProviderElementMixin.mayNeedDispose (package:riverpod/src/framework/auto_dispose.dart:40:28)
#11     ProviderElementBase._onRemoveListener (package:riverpod/src/framework/element.dart:897:5)
#12     _ExternalProviderSubscription.close (package:riverpod/src/framework/provider_base.dart:169:22)
#13     ConsumerStatefulElement.unmount (package:flutter_riverpod/src/consumer.dart:581:18)
#14     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2067:13)
#15     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2065:7)
#16     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5523:14)
#17     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2063:13)
#18     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2065:7)
#19     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5523:14)
#20     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2063:13)
#21     ListIterable.forEach (dart:_internal/iterable.dart:49:13)
#22     _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:2076:25)
#23     BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2755:15)
#24     BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:3165:7)
#25     AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1430:19)
#26     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:457:5)
#27     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325:15)
#28     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1255:9)
#29     AutomatedTestWidgetsFlutterBinding.scheduleWarmUpFrame (package:flutter_test/src/binding.dart:1355:5)
#30     runApp (package:flutter/src/widgets/binding.dart:1195:7)
#31     TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1020:7)
<asynchronous suspension>
<asynchronous suspension>
(elided 5 frames from dart:async and package:stack_trace)
```

**Comment by JoostVisser** [comment]
Indeed, that seems to fix it, thanks. 

It does not seem to work with `addTearDown(container.dispose);` (same error as above), but I can always use a different way to get the container with `ProviderScope.containerOf`, which should suit my needs.

**Comment by JoostVisser** [comment]
So I guess that's why my test cases failed when I updated from `2.4.7` to `2.4.8+`.

The following testcase did work in 2.4.7 but failed after 2.4.8+.

```dart
import 'package:fluent_ui/fluent_ui.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';

class BoolController extends AutoDisposeNotifier<bool> {
  bool build() => false;
}

final boolProvider = AutoDisposeNotifierProvider<BoolController, bool>(() {
  return BoolController();
});

void main() {
  testWidgets('Riverpod test', (tester) async {
    final container = ProviderContainer();
    addTearDown(container.dispose);

    await tester.pumpWidget(
      ProviderScope(
        child: Consumer(
          builder: (context, ref, child) {
            ref.watch(boolProvider);
            return const SizedBox();
          },
        ),
        parent: container,
      ),
    );
  });
}
``` 

Anyway, as mentioned before, my workaround is to get the container in a different way with `ProviderScope.containerOf`, but I'm mentioning it here for those that encounter the same problem.

**Comment by KoheiKanagu** [comment]
@JoostVisser Try using `UncontrolledProviderScope`.

```diff
-      ProviderScope(
+      UncontrolledProviderScope(
        child: Consumer(
          builder: (context, ref, child) {
            ref.watch(boolProvider);
            return const SizedBox();
          },
        ),
-       parent: container,
+       container: container,

```

**Comment by Maxim-Filimonov** [comment]
> @JoostVisser Try using `UncontrolledProviderScope`.
> 
> ```diff
> -      ProviderScope(
> +      UncontrolledProviderScope(
>         child: Consumer(
>           builder: (context, ref, child) {
>             ref.watch(boolProvider);
>             return const SizedBox();
>           },
>         ),
> -       parent: container,
> +       container: container,
> ```

This fixed the issue for me but I'm not sure I understand why 🤯

**Comment by JoostVisser** [comment]
> @JoostVisser Try using `UncontrolledProviderScope`.
> 
> ```diff
> -      ProviderScope(
> +      UncontrolledProviderScope(
>         child: Consumer(
>           builder: (context, ref, child) {
>             ref.watch(boolProvider);
>             return const SizedBox();
>           },
>         ),
> -       parent: container,
> +       container: container,
> ```

Hmm, I tried, but it looks like it doesn't place nicely with a periodic timer I have going on in one of my controllers (which is cancelled whenever the controller is disposed). I fixed it by manually disposing the container, but then it's a similar situation to using a `ProviderScope`.

**Comment by RafaelRV4rgas** [comment]
I fixed this by using tester.runAsync around my pump. "tester.runAsync(() => tester.pumpWidget());"
