### ISSUE TITLE
ConsumerWidget - how to access context outside of build ?

### ISSUE THREAD

**Issue by ericchuawc** [rrousselGit/river_pod#294]
Currently in StatefulWidget, I can have this

```
@override
  Widget build(BuildContext context, ScopedReader watch) {
...
}

FutureOr onGoBack(dynamic value) {
    context.read(programProvider).getProgram(id);
  }
```

The reason I need to have onGoBack, as it's being used here.

`Navigator().then(onGoBack)`

So when I go back to previous screen, it will refresh the screen.

When I used ConsumerWidget instead, somehow this code doesn't work anymore

```
FutureOr onGoBack(dynamic value) {
    context.read(programProvider).getProgram(id);
  }

```
**Undefined name 'context'**

Any ways to make this work?

**Comment by rrousselGit** [comment]
You need to pass the context from the build method to your function:

```dart
Widget build(context, reader) {
  return RaisedButton(
    onPressed: () => onGoBack(context, whatever);
  );
}

onGoBack(BuildContext context, dynamic value) {
  ...
}
```

**Comment by ericchuawc** [comment]
Hi @rrousselGit 

I don't think I can do this.

Example

**Screen 1**

Navigator().then(onGoBack) --> Screen 2

**Screen 2**

Navigator().pop() --> Go back to Screen 1 and reload page (which will call onGoBack)

How can I do this?

**Comment by rrousselGit** [comment]
What's `Navigator`?

**Comment by ericchuawc** [comment]
Here's the code snippets 

Example, based on StatefulWidget.

Basically I can do this

ProgramScreen --> ProgramDetailScreen --> ProgramScreen 

**ProgramScreen**

```
class ProgramScreen extends StatefulWidget {

...

static Future<void> show(BuildContext context) async {
    await Navigator.of(context, rootNavigator: true).pushNamed(
      ScreenRoutes.programScreen,
    );
  }

...

}

class _ProgramScreenState extends State<ProgramScreen> {

...

@override
  Widget build(BuildContext context) {

...

// Next Screen button
RaisedButton(
onPressed: () {
	ProgramDetailScreen.show(context, id).then(onGoBack);
}

)

}

// Outside build()
FutureOr onGoBack(dynamic value) {
    context.refresh(programProvider);
}

}
```

**ProgramDetailScreen**

```
class ProgramDetailScreen extends StatefulWidget {

...

static Future<void> show(BuildContext context, String id) async {
    await Navigator.of(context, rootNavigator: true).pushNamed(
      ScreenRoutes.programDetailScreen,
      arguments: {
        'id': id,
      },
    );
  }

...

}

class _ProgramDetailScreenState extends State<ProgramDetailScreen> {

..

Widget build(BuildContext context) {

...

// Back screen button
IconButton(
	onPressed: () {
		Navigator.of(context).pop();
	}
)


...

}

}
```

How can I do this in ConsumerWidget? Thanks.

**Comment by rrousselGit** [comment]
If you have a context to do the Navigator.of why can't you use it for the context.read?

**Comment by ericchuawc** [comment]
I think you mean this, by adding context as a parameter for onGoBack ?

```
FutureOr onGoBack(BuildContext context, dynamic value) {
     context.refresh(programProvider);
  }
```

Anyway I have tried it.

```
RaisedButton(
onPressed: () {
	ProgramDetailScreen.show(context, id).then(onGoBack(context)); // I am forced to add context into onGoBack()
}

```

Though I can compile and run it, it has an issue.

Based on StatefulWidget, the behaviour is this (as per debug mode).

ProgramScreen's onPressed --> ProgramDetailScreen --> ProgramDetailScreen's back button --> ProgramScreen's onGoBack

However for ConsumerWidget, this happens instead

ProgramScreen's onPressed --> ProgramScreen's onGoBack --> ProgramDetailScreen --> ProgramDetailScreen's back button --> throw error

```
[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: The method 'call' was called on null.
Receiver: null
Tried calling: call()
#0      _rootRunUnary (dart:async/zone.dart:1198:47)
#1      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#2      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#3      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#4      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#5      Future._completeWithValue (dart:async/future_impl.dart:529:5)
#6      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#7      _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#8      ProgramDetailScreen.show <asynchronous suspension>
#9      ProgramScreen.build.<anonymous closure>.<anonymous closure>.<anonymous closure>
```

Any idea? Or is there a better way to handle onGoBack for ConsumerWidget?

**Comment by rrousselGit** [comment]
The syntax is `then((_) => onGoBack(context))`

**Comment by ericchuawc** [comment]
Thanks, it works :)
