### ISSUE TITLE
[0.6.0-dev] marvel example app is broken at `ProviderScope(overrides:)`

### ISSUE THREAD

**Issue by mono0926** [rrousselGit/river_pod#65]
**Describe the bug**

As you described this, I tried to use 0.6.0-dev, but marvel example app is broken at `ProviderScope(overrides:)`.

> But the dartdoc and examples are up-to-date
> https://github.com/rrousselGit/river_pod/pull/49#issuecomment-666014458

The app doesn't work and error occurs.

Error log:

```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following UnsupportedError was thrown building NotificationListener<KeepAliveNotification>:
Unsupported operation: Cannot override providers on a non-root ProviderContainer/ProviderScope

When the exception was thrown, this was the stack:
#0      new ProviderContainer (package:riverpod/src/framework/container.dart:51:7)
#1      ProviderScopeState.initState (package:flutter_riverpod/src/framework.dart:166:17)
#2      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4695:58)
#3      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4531:5)
...     Normal element mounting (33 frames)
#36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3501:14)
#37     Element.updateChild (package:flutter/src/widgets/framework.dart:3260:18)
#38     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:1157:36)
#39     SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1142:20)
#40     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2620:19)
#41     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:1135:11)
#42     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:356:23)
#43     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1879:58)
#44     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:927:15)
#45     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1879:13)
#46     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:345:5)
#47     RenderSliverMultiBoxAdaptor.addInitialChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:429:5)
#48     RenderSliverGrid.performLayout (package:flutter/src/rendering/sliver_grid.dart:550:12)
#49     RenderObject.layout (package:flutter/src/rendering/object.dart:1776:7)
#50     RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:137:11)
#51     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:377:11)
#52     RenderObject.layout (package:flutter/src/rendering/object.dart:1776:7)
#53     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:471:13)
#54     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1465:12)
#55     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1374:20)
#56     RenderObject.layout (package:flutter/src/rendering/object.dart:1776:7)
#57     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#58     RenderObject.layout (package:flutter/src/rendering/object.dart:1776:7)
#59     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#60     RenderObject.layout (package:flutter/src/rendering/object.dart:1776:7)
#61     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#62     RenderObject.layout (package:flutter/src/rendering/object.dart:1776:7)
#63     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#64     RenderObject.layout (package:flutter/src/rendering/object.dart:1776:7)
#65     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#66     RenderObject.layout (package:flutter/src/rendering/object.dart:1776:7)
#67     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#68     RenderObject.layout (package:flutter/src/rendering/object.dart:1776:7)
#69     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#70     RenderObject.layout (package:flutter/src/rendering/object.dart:1776:7)
#71     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#72     RenderObject.layout (package:flutter/src/rendering/object.dart:1776:7)
#73     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#74     RenderObject.layout (package:flutter/src/rendering/object.dart:1776:7)
#75     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:173:11)
#76     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:497:7)
#77     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:242:7)
#78     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:401:14)
#79     RenderObject.layout (package:flutter/src/rendering/object.dart:1776:7)
#80     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#81     RenderObject.layout (package:flutter/src/rendering/object.dart:1776:7)
#82     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#83     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1269:11)
#84     RenderObject.layout (package:flutter/src/rendering/object.dart:1776:7)
#85     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#86     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1639:7)
#87     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:896:18)
#88     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:404:19)
#89     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:881:13)
#90     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
#91     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
#92     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1056:9)
#93     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:972:5)
#97     _invoke (dart:ui/hooks.dart:253:10)
#98     _drawFrame (dart:ui/hooks.dart:211:3)
(elided 3 frames from dart:async)
```

**To Reproduce**

At https://github.com/rrousselGit/river_pod/tree/v0.6.0-dev, run`examples/marvel/lib/main.dart`.

**Expected behavior**

The app works without any errors.

**Comment by rrousselGit** [comment]
Indeed. It's waiting for `ScopedProvider`

**Comment by mono0926** [comment]
Oh I see, thanks!

> It's lacking a changelog; ScopedProvider is not yet implemented, and https://riverpod.dev isn't updated yet.

Indeed, you clarified that, so I'm closing the issue.
