### ISSUE TITLE
TextEditingController in a Provider used after being disposed

### ISSUE THREAD

**Issue by buraktabn** [rrousselGit/river_pod#724]
**Describe the bug**
Trying to use `TextEditingController` in a `Provider`. When I use it with `.autoDispose` it throws an error. Without it, works fine but can't dispose it.

In my app, I need to edit the `TextEditingController` from other Providers. I don't know if this is the best practice here. I'm having a hard time working on form fields with RiverPod.

**To Reproduce**
[Sample app](https://github.com/buraktabn/riverpod_textcontroller)
```dart
class Home extends ConsumerWidget {
  const Home({Key? key}) : super(key: key);

  static final textController = Provider.autoDispose<TextEditingController>((ref) {
    final controller = TextEditingController();

    ref.onDispose(() {
      controller.dispose();
    });

    return controller;
  });

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            TextField(
              controller: ref.read(textController),
            ),
            ElevatedButton(
              onPressed: () {},
              child: const Text('Click me'),
            ),
          ],
        ),
      ),
    );
  }
}
```

<details>
  <summary>Exception</summary>
  
```
════════ Exception caught by gesture ═══════════════════════════════════════════
The following assertion was thrown while handling a gesture:
A TextEditingController was used after being disposed.

Once you have called dispose() on a TextEditingController, it can no longer be used.
When the exception was thrown, this was the stack
#0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure>
package:flutter/…/foundation/change_notifier.dart:114
#1      ChangeNotifier._debugAssertNotDisposed
package:flutter/…/foundation/change_notifier.dart:120
#2      ChangeNotifier.notifyListeners
package:flutter/…/foundation/change_notifier.dart:288
#3      ValueNotifier.value=
package:flutter/…/foundation/change_notifier.dart:412
#4      TextEditingController.value=
package:flutter/…/widgets/editable_text.dart:186
#5      EditableTextState._value=
package:flutter/…/widgets/editable_text.dart:1988
#6      EditableTextState._formatAndSetValue
package:flutter/…/widgets/editable_text.dart:2310
#7      EditableTextState.userUpdateTextEditingValue
package:flutter/…/widgets/editable_text.dart:2532
#8      RenderEditable._setTextEditingValue
package:flutter/…/rendering/editable.dart:597
#9      RenderEditable._setSelection
package:flutter/…/rendering/editable.dart:617
#10     RenderEditable.selectPositionAt
package:flutter/…/rendering/editable.dart:3405
#11     RenderEditable.selectPosition
package:flutter/…/rendering/editable.dart:3381
#12     _TextFieldSelectionGestureDetectorBuilder.onSingleTapUp
package:flutter/…/material/text_field.dart:112
#13     _TextSelectionGestureDetectorState._handleTapUp
package:flutter/…/widgets/text_selection.dart:1471
#14     TapGestureRecognizer.handleTapUp.<anonymous closure>
package:flutter/…/gestures/tap.dart:606
#15     GestureRecognizer.invokeCallback
package:flutter/…/gestures/recognizer.dart:193
#16     TapGestureRecognizer.handleTapUp
package:flutter/…/gestures/tap.dart:606
#17     BaseTapGestureRecognizer._checkUp
package:flutter/…/gestures/tap.dart:296
#18     BaseTapGestureRecognizer.acceptGesture
package:flutter/…/gestures/tap.dart:267
#19     GestureArenaManager.sweep
package:flutter/…/gestures/arena.dart:157
#20     GestureBinding.handleEvent
package:flutter/…/gestures/binding.dart:444
#21     GestureBinding.dispatchEvent
package:flutter/…/gestures/binding.dart:420
#22     RendererBinding.dispatchEvent
package:flutter/…/rendering/binding.dart:278
#23     GestureBinding._handlePointerEventImmediately
package:flutter/…/gestures/binding.dart:374
#24     GestureBinding.handlePointerEvent
package:flutter/…/gestures/binding.dart:338
#25     GestureBinding._flushPointerEventQueue
package:flutter/…/gestures/binding.dart:296
#26     GestureBinding._handlePointerDataPacket
package:flutter/…/gestures/binding.dart:279
#30     _invoke1 (dart:ui/hooks.dart:183:10)
#31     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:285:7)
#32     _dispatchPointerDataPacket (dart:ui/hooks.dart:96:31)
(elided 3 frames from dart:async)
Handler: "onTapUp"
Recognizer: TapGestureRecognizer#57296
    debugOwner: _TextSelectionGestureDetectorState#43a97
    state: ready
    won arena
    finalPosition: Offset(154.9, 371.6)
    finalLocalPosition: Offset(154.9, 29.1)
    button: 1
    sent tap down
════════════════════════════════════════════════════════════════════════════════
```
</details>
<Please add a small sample to that can be executed to reproduce the problem. As a general rule, 100 lines is the maximum>

**Expected behavior**
I expect the sample code to work as-is, dispose the `TextEditingController` when needed.

**Comment by buraktabn** [comment]
Using `ref.watch` instead of `ref.read` seems to solve the issue. However, getting the same error after changing a screen. :cry:
