### ISSUE TITLE
Crash on Todos example

### ISSUE THREAD

**Issue by tbm98** [rrousselGit/river_pod#730]
flutter_riverpod:dev-7
flutter: dev 2.6.0-0.0pre

```
E/flutter ( 7570): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: 'package:riverpod/src/framework/scheduler.dart': Failed assertion: line 29 pos 12: '!_disposed': tried to emit updates with a disposed Scheduler
E/flutter ( 7570): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
E/flutter ( 7570): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter ( 7570): #2      _ProviderScheduler._scheduleTask (package:riverpod/src/framework/scheduler.dart:29:12)
E/flutter ( 7570): #3      _ProviderScheduler.scheduleProviderRefresh (package:riverpod/src/framework/scheduler.dart:25:5)
E/flutter ( 7570): #4      ProviderElementBase.markMustRecomputeState (package:riverpod/src/framework/base_provider.dart:642:27)
E/flutter ( 7570): #5      ProviderElementBase._didChangeDependency (package:riverpod/src/framework/base_provider.dart:758:5)
E/flutter ( 7570): #6      ProviderElementBase.notifyListeners (package:riverpod/src/framework/base_provider.dart:737:22)
E/flutter ( 7570): #7      _listenStateProvider.listener (package:riverpod/src/state_provider.dart:66:9)
E/flutter ( 7570): #8      StateNotifier.state= (package:state_notifier/state_notifier.dart:162:31)
E/flutter ( 7570): #9      StateController.state= (package:riverpod/src/state_provider.dart:25:31)
E/flutter ( 7570): #10     Toolbar.build.<anonymous closure> (package:todos/main.dart:163:39)
E/flutter ( 7570): #11     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:989:21)
E/flutter ( 7570): #12     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:198:24)
E/flutter ( 7570): #13     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:608:11)
E/flutter ( 7570): #14     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:296:5)
E/flutter ( 7570): #15     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:267:7)
E/flutter ( 7570): #16     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157:27)
E/flutter ( 7570): #17     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:444:20)
E/flutter ( 7570): #18     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:420:22)
E/flutter ( 7570): #19     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:278:11)
E/flutter ( 7570): #20     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
E/flutter ( 7570): #21     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
E/flutter ( 7570): #22     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
E/flutter ( 7570): #23     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
E/flutter ( 7570): #24     _rootRunUnary (dart:async/zone.dart:1444:13)
E/flutter ( 7570): #25     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter ( 7570): #26     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter ( 7570): #27     _invoke1 (dart:ui/hooks.dart:185:10)
E/flutter ( 7570): #28     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:293:7)
E/flutter ( 7570): #29     _dispatchPointerDataPacket (dart:ui/hooks.dart:98:31)
E/flutter ( 7570): 

======== Exception caught by gesture ===============================================================
The following Error was thrown while handling a gesture:
Instance of 'Error'

When the exception was thrown, this was the stack: 
#0      StateNotifier.state= (package:state_notifier/state_notifier.dart:173:7)
#1      StateController.state= (package:riverpod/src/state_provider.dart:25:31)
#2      Toolbar.build.<anonymous closure> (package:todos/main.dart:163:39)
#3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:989:21)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:198:24)
#5      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:608:11)
#6      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:296:5)
#7      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:267:7)
#8      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157:27)
#9      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:444:20)
#10     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:420:22)
#11     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:278:11)
#12     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
#13     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
#14     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
#15     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
#19     _invoke1 (dart:ui/hooks.dart:185:10)
#20     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:293:7)
#21     _dispatchPointerDataPacket (dart:ui/hooks.dart:98:31)
(elided 3 frames from dart:async)
Handler: "onTap"
Recognizer: TapGestureRecognizer#0d5f5
  debugOwner: GestureDetector
  state: ready
  won arena
  finalPosition: Offset(170.9, 276.7)
  finalLocalPosition: Offset(43.2, 12.7)
  button: 1
  sent tap down
====================================================================================================

======== Exception caught by widgets library =======================================================
The following assertion was thrown building Home(dirty, dependencies: [_FocusMarker, UncontrolledProviderScope], state: _ConsumerState#50e14):
setState() or markNeedsBuild() called during build.

This UncontrolledProviderScope widget cannot be marked as needing to build because the framework is already in the process of building widgets.  A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
The widget on which setState() or markNeedsBuild() was called was: UncontrolledProviderScope
The widget which was currently being built when the offending call was made was: Home
  dirty
  dependencies: [_FocusMarker, UncontrolledProviderScope]
  state: _ConsumerState#50e14
The relevant error-causing widget was: 
  Home Home:file:///Users/minhtran/dev/personal/river_pod/examples/todos/lib/main.dart:79:13
When the exception was thrown, this was the stack: 
#0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:4305:11)
#1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:4320:6)
#2      _UncontrolledProviderScopeElement._debugCanModifyProviders (package:flutter_riverpod/src/framework.dart:290:5)
#3      ProviderElementBase.notifyListeners.<anonymous closure> (package:riverpod/src/framework/base_provider.dart:722:42)
#4      ProviderElementBase.notifyListeners (package:riverpod/src/framework/base_provider.dart:724:6)
#5      ProviderElementBase._maybeRebuildState (package:riverpod/src/framework/base_provider.dart:694:9)
#6      ProviderElementBase.flush (package:riverpod/src/framework/base_provider.dart:653:5)
#7      ProviderElementBase.getExposedValue (package:riverpod/src/framework/base_provider.dart:861:5)
#8      _ProviderSubscription.read (package:riverpod/src/framework/base_provider.dart:333:29)
#9      ConsumerStatefulElement.watch (package:flutter_riverpod/src/consumer.dart:452:8)
#10     Home.build (package:todos/main.dart:89:23)
#11     _ConsumerState.build (package:flutter_riverpod/src/consumer.dart:371:19)
#12     StatefulElement.build (package:flutter/src/widgets/framework.dart:4782:27)
#13     ConsumerStatefulElement.build (package:flutter_riverpod/src/consumer.dart:430:20)
#14     HookElement.build (package:flutter_hooks/src/framework.dart:417:27)
#15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4665:15)
#16     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4840:11)
#17     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#18     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2620:33)
#19     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#20     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
#21     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1143:15)
#22     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1080:9)
#23     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
#27     _invoke (dart:ui/hooks.dart:166:10)
#28     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
#29     _drawFrame (dart:ui/hooks.dart:129:31)
(elided 3 frames from dart:async)
====================================================================================================

======== Exception caught by widgets library =======================================================
The following assertion was thrown while finalizing the widget tree:
A TextEditingController was used after being disposed.

Once you have called dispose() on a TextEditingController, it can no longer be used.
When the exception was thrown, this was the stack: 
#0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:114:9)
#1      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:120:6)
#2      ChangeNotifier.removeListener (package:flutter/src/foundation/change_notifier.dart:233:12)
#3      EditableTextState.dispose (package:flutter/src/widgets/editable_text.dart:1707:23)
#4      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:4895:11)
#5      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1883:13)
#6      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#7      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#8      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#9      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#10     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6182:14)
#11     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#12     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#13     Iterable.forEach (dart:core/iterable.dart:279:35)
#14     _DecorationElement.visitChildren (package:flutter/src/material/input_decorator.dart:1575:24)
#15     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#16     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#17     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#18     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#19     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#20     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#21     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#22     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#23     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6182:14)
#24     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#25     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#26     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#27     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#28     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#29     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#30     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#31     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#32     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6182:14)
#33     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#34     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#35     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#36     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#37     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#38     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6182:14)
#39     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#40     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#41     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6182:14)
#42     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#43     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#44     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#45     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#46     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#47     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6182:14)
#48     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#49     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#50     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#51     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#52     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#53     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6182:14)
#54     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#55     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#56     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6182:14)
#57     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#58     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#59     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#60     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#61     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#62     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#63     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#64     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#65     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#66     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#67     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#68     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#69     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#70     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#71     List.forEach (dart:core-patch/growable_array.dart:403:8)
#72     SliverMultiBoxAdaptorElement.visitChildren (package:flutter/src/widgets/sliver.dart:1441:52)
#73     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#74     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#75     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6182:14)
#76     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#77     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#78     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6297:16)
#79     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#80     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#81     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6182:14)
#82     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#83     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#84     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6182:14)
#85     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#86     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#87     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6182:14)
#88     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#89     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#90     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6182:14)
#91     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#92     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#93     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#94     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#95     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#96     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6182:14)
#97     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#98     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#99     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#100    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#101    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#102    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6182:14)
#103    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#104    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#105    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6182:14)
#106    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#107    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#108    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6182:14)
#109    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#110    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#111    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6182:14)
#112    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#113    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#114    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#115    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#116    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#117    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#118    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#119    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#120    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#121    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#122    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#123    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#124    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#125    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#126    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#127    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#128    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#129    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#130    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#131    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#132    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#133    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#134    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#135    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#136    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#137    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#138    MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6297:16)
#139    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#140    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#141    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#142    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#143    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#144    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#145    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#146    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#147    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#148    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#149    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#150    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6182:14)
#151    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#152    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#153    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#154    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#155    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#156    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6182:14)
#157    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#158    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#159    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#160    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#161    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#162    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#163    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#164    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#165    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#166    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#167    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#168    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#169    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#170    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#171    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#172    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#173    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#174    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#175    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#176    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#177    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#178    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#179    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#180    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6182:14)
#181    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#182    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#183    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6182:14)
#184    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#185    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#186    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#187    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#188    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#189    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#190    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#191    ListIterable.forEach (dart:_internal/iterable.dart:39:13)
#192    _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:1892:25)
#193    BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:2879:27)
#194    BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2510:15)
#195    BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:2878:7)
#196    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:884:19)
#197    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
#198    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1143:15)
#199    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1080:9)
#200    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
#204    _invoke (dart:ui/hooks.dart:166:10)
#205    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
#206    _drawFrame (dart:ui/hooks.dart:129:31)
(elided 3 frames from dart:async)
====================================================================================================

```

https://user-images.githubusercontent.com/52562340/131548669-2ea1077f-3218-4d3a-ab27-6954aed25812.mov

I also got similar error as below when use `provider.overrideWithValue` in my project
```
The following assertion was thrown building Home(dirty, dependencies: [_FocusMarker, UncontrolledProviderScope], state: _ConsumerState#50e14):
setState() or markNeedsBuild() called during build.

This UncontrolledProviderScope widget cannot be marked as needing to build because the framework is already in the process of building widgets.  A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
The widget on which setState() or markNeedsBuild() was called was: UncontrolledProviderScope
The widget which was currently being built when the offending call was made was: Home
```

**Comment by rrousselGit** [comment]
Thanks for the report!
