### ISSUE TITLE
ProviderElementBase._previousDependencies can be null during _maybeRebuildState

### ISSUE THREAD

**Issue by nogaten** [rrousselGit/river_pod#740]
**Describe the bug**
I use a riverpod 1.0.0-dev.7.
Sometimes `ProviderElementBase._previousDependencies` becomes null during `ProviderElementBase._maybeRebuildState()` and I get an error.

**To Reproduce**
```dart
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:riverpod/riverpod.dart';

final controlProvider = StateNotifierProvider<StateController<int>, int>((ref) {
  return StateController(0);
});

final provider1 = Provider.autoDispose<int>((ref) {
  return ref.watch(controlProvider);
});

final provider2 = Provider.family.autoDispose<int, int>((ref, value) {
  return ref.watch(provider1);
});

final provider3 = Provider.autoDispose<int>((ref) {
  return ref.watch(provider1.select((value) {
    return ref.read(provider2(value));
  }));
});

void main() {
  runApp(ProviderScope(
    child: MyApp(),
  ));
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends ConsumerWidget {
  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return Scaffold(
      body: Center(
        child: Consumer(
          builder: (context, ref, _) {
            final value = ref.watch(provider3);
            return Text('$value');
          },
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          final controller = ref.read(controlProvider.notifier);
          controller.state++;
        },
        child: const Icon(Icons.add),
      ),
    );
  }
}
```

**Expected behavior**
When I pressed the floatingActionButton, I got the following error.

```
I/flutter ( 6390): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞════════════════════════
I/flutter ( 6390): The following _CastError was thrown building
I/flutter ( 6390): UncontrolledProviderScope(dirty):
I/flutter ( 6390): Null check operator used on a null value
I/flutter ( 6390): 
I/flutter ( 6390): When the exception was thrown, this was the stack:
I/flutter ( 6390): #0      ProviderElementBase._maybeRebuildState (package:riverpod/src/framework/base_provider.dart:689:46)
I/flutter ( 6390): #1      ProviderElementBase.flush (package:riverpod/src/framework/base_provider.dart:648:5)
I/flutter ( 6390): #2      _ProviderScheduler._performRefresh (package:riverpod/src/framework/scheduler.dart:52:15)
I/flutter ( 6390): #3      _ProviderScheduler._task (package:riverpod/src/framework/scheduler.dart:38:5)
I/flutter ( 6390): #4      _UncontrolledProviderScopeElement.build (package:flutter_riverpod/src/framework.dart:300:12)
I/flutter ( 6390): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4574:15)
```

**Comment by davidmartos96** [comment]
I think that you shouldn't read a provider inside the select callback, so that could be an issue.

@nogaten  You can try replacing this:

```dart
final provider3 = Provider.autoDispose<int>((ref) {
  return ref.watch(provider1.select((value) {
    return ref.read(provider2(value));
  }));
});
```

with this:

```dart
final provider3 = Provider.autoDispose<int>((ref) {
  // Although this line is the same as "ref.watch(provider1)"
  final param = ref.watch(provider1.select((p1Value) => p1Value);
  return ref.watch(provider2(param));
});
```

**Comment by nogaten** [comment]
@davidmartos96 Thank you for your reply.
I don't think the use of read in select callback was restricted.
Sometimes I want to use read in select callback.

**Comment by rrousselGit** [comment]
Using `ref.whatever` inside `select` should be restricted. It is an oversight that the code you shared didn't throw.

**Comment by nogaten** [comment]
@rrousselGit
Thank you for your answer. I have one question.
Is it possible to use `ref.whatever` in `listen`?
For example, the code below.
I get the same error with this code.

```dart
final provider3 = Provider.autoDispose<int>((ref) {
  ref.onDispose(ref.listen<int>(provider1, (value) {
    ref.state = ref.read(provider2(value));
  }));
  return 0;
});
```

**Comment by rrousselGit** [comment]
Inside `listen,` using `ref.read` is allowed. Not `ref.watch` though

**Comment by nogaten** [comment]
@rrousselGit
I uses read in listen, but I'm getting an error.

```dart
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:riverpod/riverpod.dart';

final controlProvider = StateNotifierProvider<StateController<int>, int>((ref) {
  return StateController(0);
});

final provider1 = Provider.autoDispose<int>((ref) {
  return ref.watch(controlProvider);
});

final provider2 = Provider.family.autoDispose<int, int>((ref, value) {
  return ref.watch(provider1);
});

final provider3 = Provider.autoDispose<int>((ref) {
  ref.onDispose(ref.listen<int>(provider1, (value) {
    ref.state = ref.read(provider2(value));
  }));
  return 0;
});

void main() {
  runApp(ProviderScope(
    child: MyApp(),
  ));
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends ConsumerWidget {
  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return Scaffold(
      body: Center(
        child: Consumer(
          builder: (context, ref, _) {
            final value = ref.watch(provider3);
            return Text('$value');
          },
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          final controller = ref.read(controlProvider.notifier);
          controller.state++;
        },
        child: const Icon(Icons.add),
      ),
    );
  }
}
```
