### ISSUE TITLE
`Unsupported operation: ProviderScope was rebuilt with a different ProviderScope ancestor` under certain condition

### ISSUE THREAD

**Issue by lcdsmao** [rrousselGit/river_pod#995]
**Describe the bug**

Use `ProviderScope` in `MaterialApp.builder` and enable `Select Widget Mode` in DevTools will make riverpod throw this exception:

`Unsupported operation: ProviderScope was rebuilt with a different ProviderScope ancestor`

```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following UnsupportedError was thrown building ProviderScope(dirty, state:
ProviderScopeState#d8fea):
Unsupported operation: ProviderScope was rebuilt with a different ProviderScope ancestor

The relevant error-causing widget was:
  ProviderScope ProviderScope:file:///Users/mao/Desktop/dart/playground/lib/main.dart:12:13

When the exception was thrown, this was the stack:
#0      ProviderScopeState.build.<anonymous closure> (package:flutter_riverpod/src/framework.dart:175:9)
#1      ProviderScopeState.build (package:flutter_riverpod/src/framework.dart:180:6)
#2      StatefulElement.build (package:flutter/src/widgets/framework.dart:4782:27)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4665:15)
#4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4840:11)
#5      Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#6      StatefulElement.update (package:flutter/src/widgets/framework.dart:4872:5)
#7      Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#8      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6202:14)
#9      Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#11     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#12     StatelessElement.update (package:flutter/src/widgets/framework.dart:4746:5)
#13     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#14     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6202:14)
#15     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#16     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6202:14)
#17     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#19     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4840:11)
#20     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#21     StatefulElement.update (package:flutter/src/widgets/framework.dart:4872:5)
#22     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#23     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6202:14)
#24     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#25     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6202:14)
#26     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#28     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4840:11)
#29     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#30     StatefulElement.update (package:flutter/src/widgets/framework.dart:4872:5)
#31     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#33     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#34     StatelessElement.update (package:flutter/src/widgets/framework.dart:4746:5)
#35     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#37     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4840:11)
#38     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#39     StatefulElement.update (package:flutter/src/widgets/framework.dart:4872:5)
#40     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#41     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6202:14)
#42     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#43     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6202:14)
#44     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#45     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#46     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#47     ProxyElement.update (package:flutter/src/widgets/framework.dart:5020:5)
#48     _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:181:11)
#49     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#50     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6202:14)
#51     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#53     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4840:11)
#54     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#55     StatefulElement.update (package:flutter/src/widgets/framework.dart:4872:5)
#56     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#57     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#58     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#59     ProxyElement.update (package:flutter/src/widgets/framework.dart:5020:5)
#60     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#61     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#62     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#63     ProxyElement.update (package:flutter/src/widgets/framework.dart:5020:5)
#64     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#65     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#66     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4840:11)
#67     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#68     StatefulElement.update (package:flutter/src/widgets/framework.dart:4872:5)
#69     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#70     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#71     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#72     StatelessElement.update (package:flutter/src/widgets/framework.dart:4746:5)
#73     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#74     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#75     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#76     StatelessElement.update (package:flutter/src/widgets/framework.dart:4746:5)
#77     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#78     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6202:14)
#79     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#80     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#81     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#82     ProxyElement.update (package:flutter/src/widgets/framework.dart:5020:5)
#83     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#84     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#85     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#86     ProxyElement.update (package:flutter/src/widgets/framework.dart:5020:5)
#87     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#88     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#89     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4840:11)
#90     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#91     StatefulElement.update (package:flutter/src/widgets/framework.dart:4872:5)
#92     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#93     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#94     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4840:11)
#95     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#96     StatefulElement.update (package:flutter/src/widgets/framework.dart:4872:5)
#97     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#98     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#99     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4840:11)
#100    Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#101    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2620:33)
#102    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#103    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
#104    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1143:15)
#105    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1080:9)
#106    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
#110    _invoke (dart:ui/hooks.dart:166:10)
#111    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
#112    _drawFrame (dart:ui/hooks.dart:129:31)
(elided 3 frames from dart:async)

════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: Bad state: Tried to dispose a ProviderContainer that still has children containers.

```

**To Reproduce**

- `flutter run` this code
```dart
// lib/main.dart
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

void main() {
  runApp(ProviderScope(child: MyApp()));
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: ProviderScope(
        child: Scaffold(),
      ),
      // Remove this builder and there will be no exception
      builder: (context, child) {
        return ProviderScope(child: child!);
      },
    );
  }
}
```

- Open DevTools
- Enable `Select Widget Mode`

**Expected behavior**

No exception occurs

**Comment by lcdsmao** [comment]
***Update***

I found hot-reload `MyApp` can also trigger the exception.

This seems works:

```dart
// lib/main.dart
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

void main() {
  runApp(ProviderScope(child: MyApp()));
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: ProviderScope(
        child: Scaffold(),
      ),
      builder: (_, child) {
        return ProviderScope(
          key: GlobalObjectKey(context), // add key here
          child: child!,
        );
      },
    );
  }
}
```

Is this correct?

**Comment by rrousselGit** [comment]
Looks like a bug in Flutter

It seems like Flutter is unmounting and re-mounting the content of `builder`, which causes `ProviderScope` to use a different state. Yet it uses a GlobalKey to not unmount+remount `home`.  
So this exception is expected, and it is up to Flutter to fix the problem.

Your workaround works though.
